.. Version control
.. _git: http://git-scm.com
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com
.. _bitbucket: https://bitbucket.org/

.. Editors
.. _vim: http://www.vim.org
.. _command-t: https://wincent.com/products/command-t
.. _command-t README: http://git.wincent.com/command-t.git/blob_plain/master:/README.txt

.. Python and common libraries
.. _python: http://www.python.org
.. _python.org releases: http://www.python.org/download/releases
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: http://pypi.python.org/pypi/pip
.. _easy_install: https://pythonhosted.org/setuptools/easy_install.html
.. _wheels: https://pypi.python.org/pypi/wheel
.. _numpy: http://sourceforge.net/projects/numpy/files
.. _scipy: http://sourceforge.net/projects/scipy/files
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _pypi: http://pypi.python.org
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _macports: http://www.macports.org
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: https://github.com/b4winckler/macvim
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com

.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Nipy and friends
.. _nipy: http://nipy.org
.. _gitwash: http://github.com/matthew-brett/gitwash
.. _neurodebian: http://neuro.debian.net/

.. Licenses
.. _CC0 license: http://creativecommons.org/publicdomain/zero/1.0/legalcode

.. Friend pages
.. _docosx: http://matthew-brett.github.com/docosx
.. _developing on mac: http://matthew-brett.github.com/docosx/develop_mac.html
.. _booting macs: http://matthew-brett.github.com/docosx/booting_macs.html
.. _runtime linking on Mac:
    http://matthew-brett.github.com/docosx/mac_runtime_link.html
.. _osx legacy packaging redux:
    http://matthew-brett.github.com/docosx/osx_legacy_package_redux.html

.. This repo
.. _pydagogue issue : https://github.com/matthew-brett/pydagogue/issues

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
