.. -*- rst -*-
.. vim: ft=rst
.. Links and substitutions that might be used on more than one page

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. Version control
.. _git: https://git-scm.com/
.. _git parable: https://practical-neuroimaging.github.io/git_parable.html
.. _github: https://github.com/
.. _bitbucket: https://bitbucket.org/

.. Editors
.. _vim: https://www.vim.org/
.. _command-t: https://wincent.com/products/command-t
.. _command-t README: https://github.com/wincent/command-t/blob/main/README.md

.. Python and common libraries
.. _python: https://www.python.org/
.. _python.org releases: https://www.python.org/downloads/
.. _distutils: https://docs.python.org/2/library/distutils.html
.. _setuptools: https://pypi.org/project/setuptools/
.. _distribute: https://pypi.org/project/distribute/
.. _pip: https://pypi.org/project/pip/
.. _easy_install: https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
.. _wheels: https://pypi.org/project/wheel/
.. _numpy: https://numpy.org/
.. _scipy: https://scipy.org/
.. _matplotlib: https://matplotlib.org/
.. _old and new python versions: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
.. _nose: https://nose.readthedocs.io/en/latest/
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _ipython: https://ipython.org/

.. Virtualenv and helpers
.. _virtualenv: https://pypi.org/project/virtualenv/
.. _virtualenvwrapper: https://virtualenvwrapper.readthedocs.io/en/latest/

.. Pypi and packaging
.. _pypi: https://pypi.org/
.. _example pypi: https://pythonhosted.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg
.. _get-pip.py:
.. _install pip with get-pip.py: https://pip.pypa.io/en/stable/installation/
.. _manylinux: https://github.com/pypa/manylinux

.. Mac development
.. _macports: https://www.macports.org/
.. _github osx installation: https://github.com/git-guides/install-git#install-git-on-mac
.. _xcode: https://developer.apple.com/xcode/
.. _macvim: https://github.com/macvim-dev/macvim
.. _bdist_mpkg: https://pypi.org/project/bdist_mpkg/
.. _parallels: https://www.parallels.com/

.. Windows development
.. _mingw: http://www.mingw.org/
.. _mingw-w64: https://www.mingw-w64.org/
.. _msys: http://www.mingw.org/wiki/MSYS
.. _msys2: https://www.msys2.org/
.. _powershell: https://learn.microsoft.com/en-us/powershell/
.. _msysgit: https://gitforwindows.org/
.. _putty: https://www.chiark.greenend.org.uk/~sgtatham/putty/

.. Nipy and friends
.. _nipy: https://nipy.org/
.. _gitwash: https://github.com/matthew-brett/gitwash
.. _neurodebian: https://neuro.debian.net/

.. Licenses
.. _CC0 license: https://creativecommons.org/publicdomain/zero/1.0/legalcode

.. Friend pages
.. _docosx: https://matthew-brett.github.io/docosx/
.. _developing on mac: https://matthew-brett.github.io/docosx/develop_mac.html
.. _booting macs: https://matthew-brett.github.io/docosx/booting_macs.html
.. _runtime linking on Mac:
    https://matthew-brett.github.io/docosx/mac_runtime_link.html
.. _osx legacy packaging redux:
    https://matthew-brett.github.io/docosx/legacy_package_redux.html

.. This repo
.. _pydagogue issues: https://github.com/matthew-brett/pydagogue/issues

.. Curious git
.. _curious git: https://matthew-brett.github.io/curious-git
.. _curious remotes: https://matthew-brett.github.io/curious-git/curious_remotes.html
.. _curious object types: https://matthew-brett.github.io/curious-git/git_object_types.html
.. _curious submodules: https://matthew-brett.github.io/curious-git/git_submodules.html
.. _curious push: https://matthew-brett.github.io/curious-git/git_push_algorithm.html
.. _curious reading: https://matthew-brett.github.io/curious-git/reading_git_objects.html

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
