.. Known projects

.. PROJECTNAME placeholders
.. _PROJECTNAME: https://nipy.org/
.. _`PROJECTNAME github`: https://github.com/nipy
.. _`PROJECTNAME mailing list`: https://mail.python.org/mailman3/lists/neuroimaging.python.org/

.. numpy
.. _numpy: https://numpy.org/
.. _`numpy github`: https://github.com/numpy/numpy
.. _`numpy mailing list`: https://mail.scipy.org/mailman/listinfo/numpy-discussion

.. scipy
.. _scipy: https://scipy.org/
.. _`scipy github`: https://github.com/scipy/scipy
.. _`scipy mailing list`: https://mail.scipy.org/mailman/listinfo/scipy-dev

.. nipy
.. _nipy: https://nipy.org/nipy/
.. _`nipy github`: https://github.com/nipy/nipy
.. _`nipy mailing list`: https://mail.python.org/mailman3/lists/neuroimaging.python.org/

.. ipython
.. _ipython: https://ipython.org
.. _`ipython github`: https://github.com/ipython/ipython
.. _`ipython mailing list`: https://mail.scipy.org/mailman/listinfo/IPython-dev

.. dipy
.. _dipy: https://nipy.org/dipy/
.. _`dipy github`: https://github.com/Garyfallidis/dipy
.. _`dipy mailing list`: https://mail.python.org/mailman3/lists/neuroimaging.python.org/

.. nibabel
.. _nibabel: https://nipy.org/nibabel/
.. _`nibabel github`: https://github.com/nipy/nibabel
.. _`nibabel mailing list`: https://mail.python.org/mailman3/lists/neuroimaging.python.org/

.. marsbar
.. _marsbar: https://marsbar-toolbox.github.io/
.. _`marsbar github`: https://github.com/matthew-brett/marsbar
.. _`MarsBaR mailing list`: https://sourceforge.net/projects/marsbar/lists/marsbar-users
