name: Linkcheck

on:
  push:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Linkcheck
        run: make linkcheck
